spring.application.name=shop_backend
# C?u h�nh k?t n?i c? s? d? li?u PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/shop_db
spring.datasource.username=postgres
spring.datasource.password=nhochoro

# C?u h�nh JPA v� Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect