# Cáº¥u hÃ¬nh cho mÃ´i trÆ°á»ng Development
spring.datasource.url=jdbc:postgresql://localhost:5432/shop_db
spring.datasource.username=postgres
spring.datasource.password=1

# Báº­t log SQL Äá» dá» debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Váº«n giá»¯ update Äá» tiá»n phÃ¡t triá»n, nhÆ°ng sáº½ táº¯t á» production
spring.jpa.hibernate.ddl-auto=update
