# Cáº¥u hÃ¬nh cho mÃ´i trÆ°á»ng Development
spring.datasource.url=jdbc:postgresql://localhost:5432/shop
spring.datasource.username=postgres
spring.datasource.password=511007

# Báº­t log SQL Äá» dá» debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Váº«n giá»¯ update Äá» tiá»n phÃ¡t triá»n, nhÆ°ng sáº½ táº¯t á» production
spring.jpa.hibernate.ddl-auto=update

spring.security.oauth2.client.registration.google.client-id=758520677856-j98pg9k2fju9545q0ffffmsnr9b1qtk9.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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