spring.application.name=shop_backend

# --- JWT Configuration ---
app.jwt.secret=ChuoiBiMatCucDaiVaAnToanCuaBanPhaiDuocThayDoiNgay
app.jwt.access-token-expiration-ms=3600000
app.jwt.refresh-token-expiration-ms=86400000


# ===================================================================
# DATABASE CONNECTION (POSTGRESQL)
# ===================================================================
# Thay thế 'AsmJava5DB', 'postgres', và 'your_password' bằng thông tin CSDL của bạn
spring.datasource.url=jdbc:postgresql://localhost:5432/shop
spring.datasource.username=postgres
spring.datasource.password=511007
spring.datasource.driver-class-name=org.postgresql.Driver

# ===================================================================
# JPA / HIBERNATE CONFIGURATION
# ===================================================================
# 'update': Hibernate sẽ tự động cập nhật schema CSDL khi Entity thay đổi.
# Rất hữu ích trong quá trình phát triển. Chuyển sang 'validate' khi deploy.
spring.jpa.hibernate.ddl-auto=update

# Hiển thị các câu lệnh SQL mà Hibernate thực thi trong console
spring.jpa.show-sql=true

# Cấu hình dialect cho PostgreSQL để Hibernate sinh ra câu lệnh SQL tối ưu
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Định dạng các câu lệnh SQL cho dễ đọc
spring.jpa.properties.hibernate.format_sql=true

# ===================================================================
# VIEW RESOLVER CONFIGURATION (FOR JSP FRAGMENTS IN THYMELEAF)
# ===================================================================
#spring.mvc.view.prefix=/WEB-INF/views/
#spring.mvc.view.suffix=.jsp

# ===================================================================
# MAIL SENDER CONFIGURATION
# ===================================================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=binhminh51107@gmail.com
spring.mail.password=hrkmxnjkiegzewzg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true